kind: pipeline
name: default

steps:
- name: hadolint
  image: hadolint/hadolint:latest-debian
  commands:
    - hadolint --version
    - hadolint Dockerfile

- name: linkcheck
  image: testthedocs/cci-linkcheck
  commands:
    - su-exec ttd /usr/local/bin/linkcheck -c '200,301,302' -t 5 README.md
